### ISSUE TITLE
Chốt tên đề tài 

### ISSUE THREAD

**Issue by sonnguyezz** [Thuaanf/SE03-Group15#1]

**Comment by sonnguyezz** [comment]
làm quản lí các món ăn ở nhà hàng được ko m??

**Comment by sonnguyezz** [comment]
và m làm nhóm trưởng nhé Thuần :))

**Comment by Thuaanf** [comment]
cũng được. Mà nhà hàng bán đồ ăn gì đây :))

**Comment by sonnguyezz** [comment]
các món ăn ở nhà hàng thôi, nhóm có 2 người nên ko làm cầu kì quá được

**Comment by sonnguyezz** [comment]
chốt tên đề tài thế này nhé, m tìm hiểu dần Spring MVC đi nhé

**Comment by Thuaanf** [comment]
Ok

**Comment by sonnguyezz** [comment]
ngoài bàn ở đây thì còn mang lap lên trường để làm nữa
