### ISSUE TITLE
Tạo Database

### ISSUE THREAD

**Issue by Thuaanf** [Thuaanf/SE03-Group15#2]

**Comment by sonnguyezz** [comment]
t nghĩ với đề tài này chỉ cần có bàn số bao nhiêu, gọi món gì, giá từng mòn rồi tổng tiền thôi

**Comment by Thuaanf** [comment]
ơ thế bây giờ có khánh đặt bàn trước hoặc tiệc tùng gì đấy thì như nào. Chắc cũng phải cho đặt chứ nhỉ

**Comment by sonnguyezz** [comment]
cũng phải làm thôi
